### PR TITLE
Add store commands

### PR DESCRIPTION
**Pull request by hlohaus**
Add store commands

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
Why is this not part of platform? I am missing a version constraint for CI deployments to install a specific version.

**Comment by hlohaus** [comment]
Let's see what @shopwareBot says

**Comment by hlohaus** [comment]
Example:
````
bin/console store:login -iavency -pPasssWord -uadmin -gshopware6.avency.de
bin/console store:download -pSwagPlatformDemoData
bin/console plugin:install --activate --clearCache SwagPlatformDemoData
````

**Comment by hlohaus** [comment]
https://github.com/shopware/platform/pull/596

**Pull request closed without merging**
