### PR TITLE
Master - Do not ignore var/plugins.json

### PR DESCRIPTION
**Pull request by Schrank**
Do not ignore var/plugins.json

After slack discussion:
image

### CODE REVIEW

**Comment by philipreinken** [comment]
Hi @Schrank , thank you for creating this pull request 🙂 AFAICT Stephan already pointed out that we purposely don't check in this file - would you mind clarifying your usecase for a static plugin.json once more?

**Comment by Schrank** [comment]
@philipgatzka It seems that we have a misunderstanding here and with Stephan as well 😅 

```
/var/*
[...]
!/var/plugins.json
```

BEFORE the PR we ignore everything in /var/ EXCEPT plugins.json (and a few others)
by removing this line, we ignore plugins.json as well. That is what Stephan said in the slack chat - correct me if I understood something wrong.

What this PR does: Make sure to NOT put plugins.json into version control but instead auto generate it on each and every system and keep them separated.

**Comment by mitelg** [comment]
we should make the change only on the `6.4` branch. it will be used as the upcoming 6.4.0.0 release. so `master` and `6.3` are old and not used anymore

**Comment by amenk** [comment]
Shouldn't the file itself also be deleted from git? https://github.com/shopware/production/blob/master/var/plugins.json

**Comment by icedream** [comment]
First of all, I agree with @amenk, if the file is ignored it should be completely removed from the Git repository.

I would also additionally like to ask about how to handle compiling the JavaScript bundle with Webpack **in Continous Integration** then: It required a ready made `var/plugins.json` to know which JavaScripts to include from apps/plugins (hence `bundle:dump` exists and is called from the build scripts in bin/). Up until now, I have handled this by checking in the plugins.json respectively. I tried asking this question in Slack but got no response. Did this change somehow in Shopware 6.4?

**Pull request closed without merging**
