### PR TITLE
Remove psalm in production template

### PR DESCRIPTION
**Pull request by silviokennecke**
Kernel.php does not exist anymore in src directory, as it's covered by shopware/core. The exclusion from psalm is therefor not needed anymore.

### CODE REVIEW

**Comment by shyim** [comment]
You can delete that entire file I guess

**Comment by silviokennecke** [comment]
Okay, I'll delete the file...

**Comment by silviokennecke** [comment]
@shyim Is there a reason, psalm can still be found in `.gitlab-ci/tools/composer.json`?

**Comment by shyim** [comment]
delete it too from there and maybe gitlab ci if it uses it

**Comment by silviokennecke** [comment]
At least I wasn't able to find `psalm` in the `.gitlab-ci.yml`

**Comment by keulinho** [comment]
Thanks for your contribution, your changes are merged now! :tada: :blue_heart:

**Pull request closed without merging**
