### PR TITLE
Add Danish flag as asset for the installer

### PR DESCRIPTION
**Pull request by wexotht**

### CODE REVIEW

**Comment by NiklasLimberg** [comment]
Thank you for your contribution

**Comment by wexotht** [comment]
@shyim @NiklasLimberg did something go wrong with this merge?
https://github.com/shopware/production/commit/46fc6ae60fb84f21d94e79ae171de502bb5b68a7 
It's not in the current release:
https://github.com/shopware/production/tree/v6.4.4.1/public/recovery/assets/common/images/flags

**Comment by mitelg** [comment]
@wexotht it was probably merged after we split up the release branch from trunk

**Comment by wexotht** [comment]
@mitelg okay, but what can we do to fix it? :) Do I have to do something (if yes, what?) or will you guys take it from here?

**Comment by mitelg** [comment]
no, everything is fine, no need for you to do something :blush: 

as it is on trunk, it will simply be part of the next release :wink:

**Comment by ioanok** [comment]
The image flag is part of production template but not part of the recovery repository https://github.com/shopware/recovery/tree/v6.4.7.0/Resources/public/assets/common/images/flags 

During installation we have
`"bin/console system:install`
 which will execute 
`assets:install`
 and this will overwrite everything in /public/recovery by executing 
https://github.com/shopware/core/blob/trunk/Framework/Plugin/Util/AssetService.php#L71

**Pull request closed without merging**
