### PR TITLE
composer post-*-scripts using $PHP_BINARY

### PR DESCRIPTION
**Pull request by riconeitzel**
composer scripts should run with the same interpreter as composer

### CODE REVIEW

**Comment by shyim** [comment]
Fixes #26

**Comment by JoshuaBehrens** [comment]
Is it better to use `$PHP_BINARY` instead of `@php` (https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts)?

**Comment by shyim** [comment]
I would also prefer `@php`. $PHP_BINARY is for shell scripts

**Comment by riconeitzel** [comment]
`@php` refers to the default interpreter found with `which php` while `$PHP_BINARY` refers to the binary that composer is currently executed with.

Example:

`/usr/local/bin/php80 composer install`

Here `@php` would still use `/usr/local/bin/php` instead and lead to possible errors.

**Comment by shyim** [comment]
Are you sure? The documentation says something else: https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts
> To execute PHP scripts, you can use @php which will automatically resolve to whatever php process is currently being used

The code looks also same:

https://github.com/composer/composer/blob/0021758e0bcf964237a56cb22e2f0309118b6a3f/src/Composer/EventDispatcher/EventDispatcher.php#L275-L279

vs 

https://github.com/composer/composer/blob/0021758e0bcf964237a56cb22e2f0309118b6a3f/src/Composer/EventDispatcher/EventDispatcher.php#L332

**Comment by riconeitzel** [comment]
Let me verify again, but I usually run into the issue.

**Comment by J-Rahe** [comment]
@riconeitzel, any news on this?

**Comment by riconeitzel** [comment]
not yet, I'm sorry :-/ buried in work at the moment. It's still on my to do list.

**Comment by J-Rahe** [comment]
no problem.
I will try to ping you before time runs out, you can also of course always reopen an PR should you not make it in time.

**Comment by riconeitzel** [comment]
Hi there,

tried it, failed:

```shell

> pre-update-cmd: [ ! -f vendor/autoload.php ] || @php bin/console system:update:prepare
Executing command (CWD): [ ! -f vendor/autoload.php ] || @php bin/console system:update:prepare
sh: @php: command not found
Script [ ! -f vendor/autoload.php ] || @php bin/console system:update:prepare handling the pre-update-cmd event returned with error code 127

```


If I'm not wrong this limitation breaks it:

_One limitation of this is that you can not call multiple commands in a row like @php install && @php foo. You must split them up in a JSON array of commands._

So before we have to write everything to a JSON Array of commands (where I have no Idea how to make them || combined) let's just use `$PHP_BINARY` instead?

**Comment by shyim** [comment]
Yes its ok :+1:

**Comment by J-Rahe** [comment]
Hey @riconeitzel, your PR just got merged : ) thanks!

**Pull request closed without merging**
